### PR TITLE
Use `isVisible` instead of CSS selector for extract

### PR DESCRIPTION
**Pull request by fcollonval**
@hadim Thx to that [discussion](https://discourse.jupyter.org/t/add-entries-to-the-filebrowser-contextmenu/1651/4). I figure out an other way to show the extract archive entry for specific file extensions. This may be more appropriate?

### CODE REVIEW

**Comment by hadim** [comment]
CSS selector looks like a clean way to do it. But I am confused about the relation of this PR with https://github.com/hadim/jupyter-archive/pull/24.

**Comment by fcollonval** [comment]
There is no relation with #24.

Submenu cannot be handled through `command.isVisible` as the command is linked to the subitems and not the main one. So in #24, the menu item is disposed and recreate if the user switch from submenu selection to a specific archive format (and vice-versa).

**Comment by hadim** [comment]
Oops, I totally misread. Sorry for the noise :-)

**Comment by fcollonval** [comment]
No prob, thank you for pushing forward this great extension.

**Comment by hadim** [comment]
Three block of code are conflicting with `master` now. I'll merge once it is solved.

**Comment by fcollonval** [comment]
Sorry I solve the conflict with the Web UI; that was definitely a bad idea. I'll commit quickly the fix in another PR.

**Comment by hadim** [comment]
Ahah, a classic :-)

It's all good now, no worry.

**Pull request merged**
