### PR TITLE
Remove duplicated call to compress api

### PR DESCRIPTION
**Pull request by fcollonval**
Remove the duplicated call to archive endpoint (once by `ServerConnection.makeRequest` and once by emulating a click). This is coherent with the download file implemented in Jupyterlab:
https://github.com/jupyterlab/jupyterlab/blob/1293dd2dadf888d25cc188ef543f4db6c0133d3b/packages/filebrowser/src/model.ts#L324

### CODE REVIEW

**Comment by hadim** [comment]
Make sense to me. The only thing is that we cannot check for `response.status !== 200`, but I guess it's ok.

**Comment by hadim** [comment]
Looks like there are some conflicts. Can you fix them before I merge?

**Comment by hadim** [comment]
Done. Thanks for all the help!

**Comment by fcollonval** [comment]
Thx for solving the conflicts.

**Pull request merged**
