### PR TITLE
Select format through submenu

### LINKED ISSUE #8: head method not needed
I think the head method for the handler is not needed. 

https://github.com/hadim/jupyter-archive/blob/55fbf191ab3b055e304de05e8b4b9e7af6583afa/jupyter_archive/handlers.py#L48
It's useful only for file to get some information on them without their content.

### PR DESCRIPTION
**Pull request by fcollonval**
There are more changes than expected in this PR. To summarize:

- Allow the user to pick the archive format by introducing a submenu in the context menu
- Correct the creation of archive for `tar.*` format (the resulting archive files were not valid before)
- don't use `await` in backend because it has been introduce in Python 3.7. But notebook support python >=3.5

### CODE REVIEW

**Comment by hadim** [comment]
- I thought about the submenu already but I prefer to keep it simple. I really don't like menus with plenty of options. I think it's bad in terms of UX. Moreover, 99% of the user will not care about the archive format and for those who care we should just add a setting in JLab for it.

- What was wrong with `tar.` archives?

-  `await` should be replaced by `yield from`.

**Comment by hadim** [comment]
I will commit the fix for Python 3.5 to https://github.com/hadim/jupyter-archive/pull/14

**Comment by hadim** [comment]
@fcollonval if this feature is really important for you, I am not against it and we could think about adding it.

Also, what do you think about the alternative of having and option in JLab?

**Comment by fcollonval** [comment]
Hey @hadim, sorry for the late answer. We may even do both 😄 Like if the option is `null`, we use a submenu otherwise there is an unique entry with the chosen format.

> What was wrong with tar. archives?

I was trying to save the `octet-stream` to test the content in the unit tests. But I cannot figure out how to achieve that. But to answer your question, if you try to open the archive file using usual linux tool, you will end up with error about the compression type being improper.

> await should be replaced by yield from.

Thx for the tip.

Side note for running blocking function as coroutine, tornado advices to use `run_in_executor`:
https://www.tornadoweb.org/en/stable/guide/coroutines.html#calling-blocking-functions

**Comment by hadim** [comment]
Nice idea about the submenu being dynamic if the setting is null. So far I haven't been able to read/save settings in JLab in the extension (I didn't try a lot).

Last thing about the submenu, I would prefer to have the default option to be `zip` if possible.

**Comment by hadim** [comment]
I guess we can close here.

**Pull request closed without merging**
