### PR TITLE
Simplify asynchronous compression

### PR DESCRIPTION
**Pull request by fcollonval**
@hadim I thought of this solution for the asynchronous compression running in another executor. It works well on my system. If it works for you, that may be simpler to maintain compare to the current master. If you think otherwise, you can close this PR.

### CODE REVIEW

**Comment by hadim** [comment]
Nice implementation. Simpler it's true. What I like in the one in `master` is flushing independently of `writer.add` with a timer using `ARCHIVE_DOWNLOAD_FLUSH_DELAY`. It makes flushing constant and avoids being blocked during the writing of large files.

That being said I see you're using `run_in_executor` on `archive.add` so your implementation might be nonblocking even on large files. I need to test it to confirm.

If we merge this PR could you try avoiding using `os.path` and use `pathlib` instead whenever you can?

**Comment by hadim** [comment]
Once `os.path` has been replaced by `pathlib` equivalent calls, LGTM.

**Comment by fcollonval** [comment]
I had a second thought to this. Your current solution is probably more robust if the folder contains huge files as it will flush the compressed flow progressively instead of waiting for the entire file to be processed in this PR (and keeping it in the server memory). What do you think?

**Comment by hadim** [comment]
Ok if you agree with my initial feeling then we are going to keep the `master` implementation.

**Pull request closed without merging**
